
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME=powerlevel10k/powerlevel10k

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git git-extras python sublime sudo)

source $ZSH/oh-my-zsh.sh

# Zsh completions
fpath=(/usr/local/share/zsh-completions $fpath)

autoload -Uz compinit
zstyle ':completion:*' menu select
fpath+=~/.zfunc

# Let's get sourced!
alias src="source ~/.zshrc"
alias sourcerc="source ~/.zshrc"

# Config aliases
alias zshconfig="st ~/.zshrc"
alias zshrc="st ~/.zshrc"
alias ohmyzsh="~/.oh-my-zsh"
alias bashconfig="st ~/.bash_profile"
alias tmuxconf="st ~/.tmux.conf"

# Make some basic commands verbose
alias rm="rm -v"
alias cp="cp -v"
alias mv="mv -v"

# Generic command aliases
alias clr="clear"

# Python Aliases
alias p="python3 -m IPython"
alias sourcevenv="source venv/bin/activate"

# Git aliases
alias gsl="git stash list"
alias gsp="git stash pop"
alias gs="git stash"
alias gsm="git stash push -m"
