
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[[ -d /opt/brew/share/zsh/site-functions/ ]] && fpath+=(/opt/brew/share/zsh/site-functions/)

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME=powerlevel10k/powerlevel10k

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git git-extras poetry python sublime sudo)

source $ZSH/oh-my-zsh.sh

# Directories
export WORKON_HOME=$HOME/.virtualenvs

# Zsh completions/keybindings
fpath=(/usr/local/share/zsh-completions $fpath)

autoload -Uz compinit
bashcompinit

zstyle ':completion:*' menu select
fpath+=~/.zfunc

# pipx completion
eval "$(register-python-argcomplete pipx)"

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Path additions
pathadd() {
    if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        PATH="$1${PATH:+":$PATH"}"
    fi
}

pathadd "$HOME/.local/bin"
pathadd "/opt/homebrew/bin"
pathadd "/usr/local/bin"

# Let's get sourced!
alias src="source ~/.zshrc"
alias sourcerc="source ~/.zshrc"

# Config aliases
alias zshconfig="st ~/.zshrc"
alias zshrc="st ~/.zshrc"
alias ohmyzsh="~/.oh-my-zsh"
alias bashconfig="st ~/.bash_profile"
alias tmuxconf="st ~/.tmux.conf"

# Make some basic commands verbose
alias rm="rm -v"
alias cp="cp -v"
alias mv="mv -v"

# Generic command aliases
alias o="open ."
alias clr="clear"

# Generic folder aliases
alias dotfiles="~/dotfiles"

alias docs="~/Documents"
alias doc="~/Documents"
alias documents="~/Documents"

alias dl="~/Downloads"
alias dls="~/Downloads"
alias down="~/Downloads"
alias downloads="~/Downloads"

# Python Aliases
alias p="python3 -m IPython"
alias sourcevenv="source venv/bin/activate"
alias pew='python3 -m pew'

# Tmux Aliases
alias tmn="tmux new -s"
alias tma="tmux attach -t"
alias tmls="tmux ls"

# Git aliases
alias gsl="git stash list"
alias gsp="git stash pop"
alias gs="git stash"
alias gsm="git stash push -m"

# Docker Compose Aliases
alias dc="docker-compose"
alias sdc="sudo docker-compose"
