---
- name: Install global python packages
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: /usr/bin/pip3
  with_items: "{{ global_python_packages }}"

- name: Install pipx packages
  community.general.pipx:
    name: "{{ item }}"
    executable: "{{ homebrew_prefix }}/bin/pipx"
  with_items: "{{ pipx_packages }}"
