---
- name: Install macOS command-line tools
  include_role:
    name: elliotweiser.osx-command-line-tools

- name: Install Homebrew and Homebrew packages
  include_role:
    name: geerlingguy.mac.homebrew
  vars:
    homebrew_installed_packages: "{{ brew_packages }}"
    homebrew_cask_apps: "{{ brew_cask_packages }}"
    homebrew_cask_accept_external_apps: true

- name: Install Mac App Store apps
  include_role:
    name: geerlingguy.mac.mas
  vars:
    mas_installed_apps: "{{ mas_apps }}"
