---
- name: Authorize SSH for GitHub
  when: ansible_distribution != 'MacOSX'      # TODO: run if not running on localhost
  block:
    - name: Generate SSH key pair
      community.crypto.openssh_keypair:
        path: "{{ ansible_user_dir }}/.ssh/id_ed25519"
        type: ed25519

    - name: Read SSH public key
      ansible.builtin.shell: "cat {{ ansible_user_dir }}/.ssh/id_ed25519.pub"
      register: ssh_pub_key

    - name: Authorize SSH key with GitHub
      local_action:
        module: github_key
        name: "SSH key for {{ ansible_hostname }}"
        token: '{{ github_access_token }}'
        pubkey: '{{ ssh_pub_key.stdout }}'

- name: Automatically load SSH keys into ssh-agent
  when: ansible_distribution == 'MacOSX'
  block:
    - name: Create ~/.ssh directory if it does not exist
      file:
        path: "{{user_home}}/.ssh"
        state: directory

    - name: Determine if SSH config exists
      stat:
        path: "{{user_home}}/.ssh/config"
      register: ssh_config_stat

    - debug:
        msg: "Not modifying SSH config file, as it already exists"
      when: ssh_config_stat.stat.exists

    - name: Ensure SSH keys are automatically loaded into ssh-agent
      blockinfile:
        path: "{{user_home}}/.ssh/config"
        block: |
          Host *
            AddKeysToAgent yes
            UseKeychain yes
            IdentityFile ~/.ssh/id_rsa
        create: yes
        insertbefore: BOF
      when: not ssh_config_stat.stat.exists
