---
- name: Generate SSH key pair
  community.crypto.openssh_keypair:
    path: "{{ ansible_user_dir }}/.ssh/id_ed25519"
    type: ed25519

- name: Read SSH public key
  ansible.builtin.shell: "cat {{ ansible_user_dir }}/.ssh/id_ed25519.pub"
  register: ssh_pub_key

- name: Authorize SSH key with GitHub
  local_action:
    module: github_key
    name: "SSH key for {{ ansible_hostname }}"
    token: '{{ github_access_token }}'
    pubkey: '{{ ssh_pub_key.stdout }}'
