---
- name: Disable auto-correct
  block:
    - name: Clear existing value
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticSpellingCorrectionEnabled
        state: absent

    - name: Set value
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticSpellingCorrectionEnabled
        type: bool
        value: false
        state: present

- name: Disable auto-capitalization
  block:
    - name: Clear existing value
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticCapitalizationEnabled
        state: absent

    - name: Set value
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticCapitalizationEnabled
        type: bool
        value: false
        state: present

- name: Disable smart dashes
  block:
    - name: Clear existing value
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticDashSubstitutionEnabled
        state: absent

    - name: Set value
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticDashSubstitutionEnabled
        type: bool
        value: false
        state: present

- name: Disable smart quotes
  block:
    - name: Clear existing value
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticQuoteSubstitutionEnabled
        state: absent

    - name: Set value
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticQuoteSubstitutionEnabled
        type: bool
        value: false
        state: present

- name: Disable auto period substitution
  block:
    - name: Clear existing value
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticPeriodSubstitutionEnabled
        state: absent

    - name: Set value
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticPeriodSubstitutionEnabled
        type: bool
        value: false
        state: present

- name: Disable "natural" (Lion-style) scrolling
  block:
    - name: Clear existing value
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.swipescrolldirection
        state: absent

    - name: Set value
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.swipescrolldirection
        type: bool
        value: false
        state: present

- name: Set keyboard repeat rate
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 2
    state: present

- name: Set initial keyboard repeat rate
  block:
    - name: Clear existing value
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: InitialKeyRepeat
        state: absent

    - name: Set value
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: InitialKeyRepeat
        type: int
        value: 10
        state: present

- name: Enable trackpad tap-to-click
  block:
    - name: Clear existing value
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.mouse.tapBehavior
        state: absent

    - name: Set value
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.mouse.tapBehavior
        type: int
        value: 1
        state: present

- name: Enable full keyboard access for all controls
  block:
    - name: Clear existing value
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: AppleKeyboardUIMode
        state: absent

    - name: Set value
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: AppleKeyboardUIMode
        type: int
        value: 3
        state: present
