---
- name: Disable auto-correct
  block:
    - name: Disable auto-correct (clear)
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticSpellingCorrectionEnabled
        state: absent

    - name: Disable auto-correct (set)
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticSpellingCorrectionEnabled
        type: bool
        value: false
        state: present

- name: Disable auto-capitalization
  block:
    - name: Disable auto-capitalization (clear)
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticCapitalizationEnabled
        state: absent

    - name: Disable auto-capitalization (set)
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticCapitalizationEnabled
        type: bool
        value: false
        state: present

- name: Disable smart dashes
  block:
    - name: Disable smart dashes (clear)
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticDashSubstitutionEnabled
        state: absent

    - name: Disable smart dashes (set)
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticDashSubstitutionEnabled
        type: bool
        value: false
        state: present

- name: Disable smart quotes
  block:
    - name: Disable smart quotes (clear)
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticQuoteSubstitutionEnabled
        state: absent

    - name: Disable smart quotes (set)
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticQuoteSubstitutionEnabled
        type: bool
        value: false
        state: present

- name: Disable auto period substitution
  block:
    - name: Disable auto period substitution (clear)
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticPeriodSubstitutionEnabled
        state: absent

    - name: Disable auto period substitution (set)
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticPeriodSubstitutionEnabled
        type: bool
        value: false
        state: present

- name: Disable "natural" (Lion-style) scrolling
  block:
    - name: Disable "natural" (Lion-style) scrolling (clear)
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.swipescrolldirection
        state: absent

    - name: Disable "natural" (Lion-style) scrolling (set)
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.swipescrolldirection
        type: bool
        value: false
        state: present

- name: Set keyboard repeat rate
  block:
    - name: Set keyboard repeat rate (clear)
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: KeyRepeat
        state: absent

    - name: Set keyboard repeat rate (set)
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: KeyRepeat
        type: int
        value: 2
        state: present

- name: Set initial keyboard repeat rate
  block:
    - name: Set initial keyboard repeat rate (clear)
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: InitialKeyRepeat
        state: absent

    - name: Set initial keyboard repeat rate (set)
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: InitialKeyRepeat
        type: int
        value: 10
        state: present

- name: Enable trackpad tap-to-click
  block:
    - name: Enable trackpad tap-to-click (clear)
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.mouse.tapBehavior
        state: absent

    - name: Enable trackpad tap-to-click (set)
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.mouse.tapBehavior
        type: int
        value: 1
        state: present

- name: Enable full keyboard access for all controls
  block:
    - name: Enable full keyboard access for all controls (clear)
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: AppleKeyboardUIMode
        state: absent

    - name: Enable full keyboard access for all controls (set)
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: AppleKeyboardUIMode
        type: int
        value: 3
        state: present

- name: Remap Caps Lock to Control
  ansible.builtin.command: |
    hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc": 0x700000039, "HIDKeyboardModifierMappingDst": 0x7000000E0}]}'
