---
- name: Install Homebrew
  block:
    - name: Download Homebrew installation script
      get_url:
        url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
        dest: /tmp/brew_install

    - name: Install Homebrew
      shell: /usr/bin/ruby /tmp/install < /dev/null

- name: Update Homebrew
  homebrew:
    update_homebrew: true

- name: Install Homebrew packages
  homebrew:
    name: "{{brew_packages}}"
    state: present

- name: Install Homebrew cask packages
  homebrew_cask:
    name: "{{brew_cask_packages}}"
    state: present

- name: Install Mac App Store packages
  mas:
    id: "{{item.id}}"
    state: present
    upgrade_all: "{{mas_upgrade_all_apps}}"
  with_items: "{{mas_apps}}"
