home_latitude: None
home_longitude: None

https_api_key: None

dark_sky_api_key: None

orbi_admin_password: None

particle_photon_username: None
particle_photon_password: None

ecobee_api_key: None

smartthinq_token: None
