---
services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "8096:8096"
      - "7359:7359/udp"
    volumes:
      - /storage/media/config/jellyfin:/config
      - /storage/media/tv:/tv
      - /storage/media/movies:/movies
      - /storage/media/music:/music
