---
brew_packages:
  - zsh
  - zsh-completions
  - fzf
  - tree
  - mas
  - hub

# TODO: remove
# These are installed directly with brew now, but keeping separate because we need to check if they exist
# https://github.com/ansible-collections/community.general/issues/864
#brew_cask_packages:
#  - { name: "google-chrome",  path: "Google Chrome.app" }
#  - { name: "iterm2",         path: "iTerm.app" }
#  - { name: "hammerspoon",    path: "Hammerspoon.app" }
#  - { name: "sublime-text",   path: "Sublime Text" }
#  - { name: "pycharm-ce",     path: "PyCharm CE" }
#  - { name: "spotify",        path: "Spotify" }
#  - homebrew/cask-drivers/logitech-options
#  - messenger
#  - signal

brew_cask_packages:
  - google-chrome
  - iterm2
  - hammerspoon
  - sublime-text
  - pycharm-ce
  - spotify
  - messenger
  - signal

mas_apps:
  - name: Amphetamine
    id: 937984704

mas_upgrade_all_apps: false
