brew_packages:
  - zsh
  - zsh-completions
  - fzf
  - tree
  - mas
  - hub

  # These are historically brew cask packages
  - google-chrome
  - iterm2
  - hammerspoon
  - sublime-text
  - pycharm-ce
  - spotify
  - homebrew/cask-drivers/logitech-options
  - messenger
  - signal

mas_apps:
  - name: Amphetamine
    id: 937984704

mas_upgrade_all_apps: false
