---
services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./glance/config:/app/config
      - ./glance/assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:8080"
