brew 'zsh'
brew 'zsh-completions'
brew 'fzf'
brew 'tree'
brew 'mas'
brew 'hub'

cask 'google-chrome'
cask 'iterm2'
cask 'hammerspoon'
cask 'sublime-text'
cask 'spotify'
cask 'microsoft-office'
cask 'adobe-acrobat-reader'
cask 'homebrew/cask-drivers/logitech-options'
cask 'macdown'
cask 'messenger'

mas 'Amphetamine', id: 937984704
mas 'iStat Menus', id: 1319778037