---
- name: Get host IP address
  ansible.builtin.set_fact:
    ip_address: "{{ ansible_default_ipv4.address }}"

- name: Setup mqtt-bridge
  block:
    - name: Ensure mqtt-bridge directory exists
      ansible.builtin.file:
        path: "{{ mqtt_bridge_dir }}"
        state: directory

    - name: Build and copy mqtt-bridge config
      ansible.builtin.template:
        src: mqtt_bridge_config.yml.j2
        dest: "{{ mqtt_bridge_config }}"

- name: Copy docker-compose.yml
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "{{ docker_dir }}/docker-compose.yml"
    backup: true
