---

# Homebrew cask to install dockutil from
dockutil_homebrew_cask: hpedrorodrigues/tools/dockutil

# Ordering of tiles in macOS dock
macos_dock_persistent_apps:
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
  - name: "Safari"
    path: "/Applications/Safari.app/"
  - name: "Messages"
    path: "/Applications/Messages.app/"
  - name: "Messenger"
    path: "/Applications/Messenger.app/"
  - name: "Signal"
    path: "/Applications/Signal.app/"
  - name: "Calendar"
    path: "/Applications/Calendar.app/"
  - name: "Reminders"
    path: "/Applications/Reminders.app/"
  - name: "Notes"
    path: "/Applications/Notes.app/"
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
  - name: "PyCharm CE"
    path: "/Applications/PyCharm CE.app/"
  - name: "Sublime Text"
    path: "/Applications/Sublime Text.app/"
  - name: "Music"
    path: "/Applications/Music.app/"
  - name: "1Password 7"
    path: "/Applications/1Password 7.app/"
  - name: "System Settings"
    path: "/Applications/System Settings.app/"

macos_dock_persistent_others:
  - name: "Applications"
    path: "/Applications/"
    sort: "name"
    display: "stack"
  - name: "Downloads"
    path: "~/Downloads/"
    sort: "datemodified"
    display: "stack"
