version: "3.3"
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    restart: always
    volumes:
      - ~/docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - ~/docker/shared:/shared
    network_mode: host
