version: "3.3"
services:
  mqtt:
    container_name: mqtt-broker
    image: matteocollina/mosca
    ports:
      - 1883:1883
    network_mode: host

  mqttbridge:
    container_name: mqtt-bridge
    image: stjohnjohnson/smartthings-mqtt-bridge
    volumes:
      - ~/.dotfiles/linux/mqtt-bridge:/config
    ports:
      - 8080:8080
    network_mode: host

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    ports:
      - 80:80
      - 8123:8123
    restart: always
    volumes:
      - ~/docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - ~/docker/shared:/shared
    network_mode: host
